# Generated by Django 2.2.4 on 2019-08-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flow_type', models.PositiveIntegerField(choices=[(1, 'Normal Flow'), (2, 'Alternate Flow'), (3, 'Exceptional Flow')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_message', models.CharField(max_length=200)),
                ('ar_message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preconditions', models.TextField()),
                ('postconditions', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usecases', to='srs.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='srs.Flow')),
                ('messages', models.ManyToManyField(blank=True, null=True, related_name='steps', to='srs.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('requiremnt_type', models.PositiveIntegerField(choices=[(1, 'Functional'), (2, 'Non-Functional')], default=1)),
                ('usecases', models.ManyToManyField(blank=True, null=True, to='srs.Usecase')),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='usecase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='srs.Usecase'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('usecase', models.ManyToManyField(blank=True, null=True, related_name='actors', to='srs.Usecase')),
            ],
        ),
    ]
