# Generated by Django 2.2.4 on 2019-08-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrule',
            name='usecase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='srs.Usecase'),
        ),
    ]
