# Generated by Django 2.2.4 on 2019-09-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('inputValues', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('widgetType', models.CharField(choices=[('Text Field', 'Text Field'), ('Text Area', 'Text Area'), ('Drop Down', 'Drop Down'), ('Radio', 'Radio'), ('Checkbox', 'checkbox')], max_length=200)),
                ('valueType', models.CharField(choices=[('Numberic', 'Numberic'), ('Text', 'Text'), ('Boolean', 'Boolean')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reverseName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Normal Flow', 'Normal Flow'), ('Alternate Flow', 'Alternate Flow'), ('Exception Flow', 'Exception Flow')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('preConditions', models.CharField(max_length=2000)),
                ('postConditions', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNo', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='requirements.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='usecase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='requirements.Usecase'),
        ),
        migrations.CreateModel(
            name='LinksAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_linked', to='requirements.LinkType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='requirements.ArtifactType')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='requirements.ArtifactType')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='requirements.LinkType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='requirements.Artifact')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='requirements.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='FieldValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='requirements.Field')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactFieldValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldvalues', to='requirements.Artifact')),
                ('artifactField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='requirements.ArtifactFields')),
            ],
        ),
        migrations.AddField(
            model_name='artifactfields',
            name='artifactType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requirements.ArtifactType'),
        ),
        migrations.AddField(
            model_name='artifactfields',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='requirements.Field'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.ArtifactType'),
        ),
    ]
